"""empty message

Revision ID: 58e89c310638
Revises: ee471d378114
Create Date: 2016-06-08 17:25:23.579078

"""

# revision identifiers, used by Alembic.
revision = '58e89c310638'
down_revision = 'ee471d378114'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
