"""empty message

Revision ID: 904bc2f05179
Revises: None
Create Date: 2016-06-02 11:08:09.762261

"""

# revision identifiers, used by Alembic.
revision = '904bc2f05179'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
