"""empty message

Revision ID: a46e618f2290
Revises: 6375c365f324
Create Date: 2016-06-14 16:36:14.854741

"""

# revision identifiers, used by Alembic.
revision = 'a46e618f2290'
down_revision = '6375c365f324'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_posts_timestamp'), 'posts', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_timestamp'), table_name='posts')
    ### end Alembic commands ###
