"""empty message

Revision ID: a6de3ad6ebca
Revises: a46e618f2290
Create Date: 2016-06-14 17:15:37.143857

"""

# revision identifiers, used by Alembic.
revision = 'a6de3ad6ebca'
down_revision = 'a46e618f2290'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author_name', sa.Integer(), nullable=True))
    op.drop_constraint(u'posts_ibfk_1', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['author_name'], ['id'])
    op.drop_column('posts', 'post_author')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_author', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(u'posts_ibfk_1', 'posts', 'users', ['post_author'], ['id'])
    op.drop_column('posts', 'author_name')
    ### end Alembic commands ###
