"""empty message

Revision ID: ee471d378114
Revises: 25ea33724d93
Create Date: 2016-06-08 16:13:06.828155

"""

# revision identifiers, used by Alembic.
revision = 'ee471d378114'
down_revision = '25ea33724d93'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_author', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.drop_constraint(u'posts_ibfk_1', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['post_author'], ['id'])
    op.drop_column('posts', 'author')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(u'posts_ibfk_1', 'posts', 'users', ['author'], ['id'])
    op.drop_column('posts', 'timestamp')
    op.drop_column('posts', 'post_author')
    ### end Alembic commands ###
