"""empty message

Revision ID: fb1faec5d99e
Revises: a6de3ad6ebca
Create Date: 2016-06-14 17:21:26.498710

"""

# revision identifiers, used by Alembic.
revision = 'fb1faec5d99e'
down_revision = 'a6de3ad6ebca'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'posts_ibfk_1', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    op.drop_column('posts', 'author_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author_name', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(u'posts_ibfk_1', 'posts', 'users', ['author_name'], ['id'])
    op.drop_column('posts', 'author_id')
    ### end Alembic commands ###
