"""add post body_abstract row

Revision ID: 1b8e4f2cb14e
Revises: 359a34011f5e
Create Date: 2016-07-11 17:10:40.289981

"""

# revision identifiers, used by Alembic.
revision = '1b8e4f2cb14e'
down_revision = '359a34011f5e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_abtract', sa.Text(), nullable=True))
    op.alter_column('statistic_visitor', 'referred',
               existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=128),
               nullable=True,
               existing_server_default=sa.text(u"''"))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statistic_visitor', 'referred',
               existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=128),
               nullable=False,
               existing_server_default=sa.text(u"''"))
    op.drop_column('posts', 'body_abtract')
    ### end Alembic commands ###
