"""empty message

Revision ID: 22e832b74259
Revises: None
Create Date: 2016-05-25 16:58:51.449359

"""

# revision identifiers, used by Alembic.
revision = '22e832b74259'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test_tag', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test_tag')
    ### end Alembic commands ###
