"""add default value in referred row in  statistic visitor table

Revision ID: 359a34011f5e
Revises: 6068a3cf95bf
Create Date: 2016-07-11 09:52:33.885240

"""

# revision identifiers, used by Alembic.
revision = '359a34011f5e'
down_revision = '6068a3cf95bf'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statistic_visitor', 'referred',
               existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=128),
               nullable=True,
               existing_server_default=sa.text(u"''"))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statistic_visitor', 'referred',
               existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=128),
               nullable=False,
               existing_server_default=sa.text(u"''"))
    ### end Alembic commands ###
