"""empty message

Revision ID: 36a96e4a1040
Revises: 22e832b74259
Create Date: 2016-05-25 17:15:56.684829

"""

# revision identifiers, used by Alembic.
revision = '36a96e4a1040'
down_revision = '22e832b74259'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('time', sa.Time(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'time')
    ### end Alembic commands ###
