"""empty message

Revision ID: 3e9752c5e54d
Revises: 36a96e4a1040
Create Date: 2016-05-25 17:21:11.426147

"""

# revision identifiers, used by Alembic.
revision = '3e9752c5e54d'
down_revision = '36a96e4a1040'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('time_now', sa.Time(), nullable=True))
    op.drop_column('users', 'time')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('time', mysql.TIME(), nullable=True))
    op.drop_column('users', 'time_now')
    ### end Alembic commands ###
