"""remove unique of referred row in statistic table

Revision ID: 3eff799b3db1
Revises: 8d684695a2ec
Create Date: 2016-07-10 22:33:40.483406

"""

# revision identifiers, used by Alembic.
revision = '3eff799b3db1'
down_revision = '8d684695a2ec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('referred', table_name='statistic_visitor')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('referred', 'statistic_visitor', ['referred'], unique=True)
    ### end Alembic commands ###
