"""add body_html in posts

Revision ID: 63cb2bf4c0d1
Revises: 74b2d2ca0638
Create Date: 2016-07-09 15:01:37.905942

"""

# revision identifiers, used by Alembic.
revision = '63cb2bf4c0d1'
down_revision = '74b2d2ca0638'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
