"""add favor column in posts

Revision ID: 74b2d2ca0638
Revises: eb64b7b3d4c2
Create Date: 2016-07-08 13:37:01.423441

"""

# revision identifiers, used by Alembic.
revision = '74b2d2ca0638'
down_revision = 'eb64b7b3d4c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('favor', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'favor')
    ### end Alembic commands ###
