"""empty message

Revision ID: 87b70baa87e1
Revises: None
Create Date: 2016-06-18 20:20:13.277346

"""

# revision identifiers, used by Alembic.
revision = '87b70baa87e1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
