"""add statistic visitor table

Revision ID: 8d684695a2ec
Revises: b9a6de5f4993
Create Date: 2016-07-09 23:36:37.761742

"""

# revision identifiers, used by Alembic.
revision = '8d684695a2ec'
down_revision = 'b9a6de5f4993'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistic_visitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_count', sa.DateTime(), nullable=True),
    sa.Column('referred', sa.String(length=128), nullable=False),
    sa.Column('agent', sa.String(length=64), nullable=True),
    sa.Column('platform', sa.String(length=64), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'referred'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('referred')
    )
    op.create_index(op.f('ix_statistic_visitor_last_count'), 'statistic_visitor', ['last_count'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statistic_visitor_last_count'), table_name='statistic_visitor')
    op.drop_table('statistic_visitor')
    ### end Alembic commands ###
