"""empty message

Revision ID: 9dcf525e3c14
Revises: 10aa37389b60
Create Date: 2016-08-31 16:41:29.363434

"""

# revision identifiers, used by Alembic.
revision = '9dcf525e3c14'
down_revision = '10aa37389b60'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('realname', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_realname'), 'users', ['realname'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_realname'), table_name='users')
    op.drop_column('users', 'realname')
    ### end Alembic commands ###
