"""change referred row from string to text in table statistic_visitor

Revision ID: b2286df65ce6
Revises: 3eff799b3db1
Create Date: 2016-07-11 02:02:03.250202

"""

# revision identifiers, used by Alembic.
revision = 'b2286df65ce6'
down_revision = '3eff799b3db1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statistic_visitor', 'referred',
               existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=128),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statistic_visitor', 'referred',
               existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=128),
               nullable=False)
    ### end Alembic commands ###
