"""add some columns in machine_statistic table

Revision ID: e8b3861bce6b
Revises: 55c24cfaf201
Create Date: 2016-07-27 17:22:09.238894

"""

# revision identifiers, used by Alembic.
revision = 'e8b3861bce6b'
down_revision = '55c24cfaf201'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machine_statistic', sa.Column('gateway', sa.String(length=64), nullable=True))
    op.add_column('machine_statistic', sa.Column('ip', sa.String(length=64), nullable=True))
    op.add_column('machine_statistic', sa.Column('localip', sa.String(length=64), nullable=True))
    op.add_column('machine_statistic', sa.Column('wlanmac', sa.String(length=64), nullable=True))
    op.alter_column('statistic_visitor', 'referred',
               existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=128),
               nullable=True,
               existing_server_default=sa.text(u"''"))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statistic_visitor', 'referred',
               existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=128),
               nullable=False,
               existing_server_default=sa.text(u"''"))
    op.drop_column('machine_statistic', 'wlanmac')
    op.drop_column('machine_statistic', 'localip')
    op.drop_column('machine_statistic', 'ip')
    op.drop_column('machine_statistic', 'gateway')
    ### end Alembic commands ###
