"""add table sitedata count visitor

Revision ID: ea5ee359db0a
Revises: 63cb2bf4c0d1
Create Date: 2016-07-09 16:46:03.018979

"""

# revision identifiers, used by Alembic.
revision = 'ea5ee359db0a'
down_revision = '63cb2bf4c0d1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sitedata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visitor_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sitedata')
    ### end Alembic commands ###
