"""add view_count column in posts

Revision ID: eb64b7b3d4c2
Revises: fc532e183eaa
Create Date: 2016-07-08 11:01:40.948143

"""

# revision identifiers, used by Alembic.
revision = 'eb64b7b3d4c2'
down_revision = 'fc532e183eaa'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('view_count', sa.Integer(), nullable=True))
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', mysql.TEXT(collation=u'utf8_unicode_ci'), nullable=True))
    op.drop_column('posts', 'view_count')
    ### end Alembic commands ###
